### PR TITLE
update Fabric initialize

### PR DESCRIPTION
**Pull request by bduyng**

### CODE REVIEW

**Comment by bduyng** [comment]
fixed #22  - `Error: Must Initialize Fabric before using singleton()`

**Comment by macasfaj** [comment]
@hansemannn @bduyng Could you apply the merge and create a new release version with this update?

**Comment by Brianggalvez** [comment]
[ti.crashlytics-android-1.1.2.zip](https://github.com/hansemannn/titanium-crashlytics/files/3895559/ti.crashlytics-android-1.1.2.zip)
For me it's working, I can see the Crashlytics init log

**Comment by hansemannn** [comment]
Thx @brianggalvez!

**Pull request merged**
