### PR TITLE
Casting params to NSDictionary

### PR DESCRIPTION
**Pull request by rlustemberg**
Casting params to NSDictionary
Updated titanium.xconfig

### CODE REVIEW

**Comment by hansemannn** [comment]
Thx, great work! Can you please bump the version to the next patch version?

**Comment by rlustemberg** [comment]
I've already set the version to 1.1.1. Is that right?

**Comment by hansemannn** [comment]
Oh yes, pardon!

**Comment by hansemannn** [comment]
New release published: https://github.com/hansemannn/titanium-crashlytics/releases/tag/ios-1.1.1

**Pull request merged**
